"""Train Tempo's NNUE evaluation on `tempo datagen` output.

Architecture (perspective network, as used by most modern engines):

    768 inputs per side (colour x piece type x square, from that side's view)
      -> shared feature transformer, H hidden units (one accumulator per side)
      -> SCReLU (clamp to [0, 1], then square)
      -> concat [side to move, other side] -> 1 output

The output is an evaluation in units of SCALE centipawns. The target blends
the search score and the game result: (1 - lambda) * sigmoid(score / SCALE)
+ lambda * result, all from the side to move's view.

Weights are exported quantized (QA = 255 for the transformer, QB = 1024 for the
output layer) as a C++ header the engine compiles in, so inference is pure
integer arithmetic.

  python tools/nnue/train.py data/train.bin --hidden 256 --epochs 30 --out src/nnue_weights.h
"""

import argparse
import math
import time

import numpy as np
import torch
import torch.nn as nn

from data import decode, load

SCALE = 400
QA, QB = 255, 1024


def features(records, device):
    """Feature indices for both perspectives, ordered (side to move, other)."""
    piece, square, _ = decode(records)
    valid = piece >= 0
    color, ptype = piece // 6, piece % 6
    white_view = color * 384 + ptype * 64 + square
    black_view = (1 - color) * 384 + ptype * 64 + (square ^ 56)
    stm_black = (records["stm"] == 1)[:, None]
    us = np.where(stm_black, black_view, white_view)
    them = np.where(stm_black, white_view, black_view)
    # EmbeddingBag with per_sample_weights: padding slots get weight 0.
    us = np.where(valid, us, 0)
    them = np.where(valid, them, 0)
    w = valid.astype(np.float32)
    t = lambda a, dt: torch.from_numpy(np.ascontiguousarray(a)).to(device, dt, non_blocking=True)
    return t(us, torch.long), t(them, torch.long), t(w, torch.float32)


def targets(records, lam, device):
    sign = np.where(records["stm"] == 0, 1.0, -1.0)
    score = records["score"].astype(np.float32) * sign
    result = records["result"].astype(np.float32) / 2.0
    result = np.where(sign > 0, result, 1.0 - result)
    target = (1 - lam) / (1 + np.exp(-score / SCALE)) + lam * result
    return torch.from_numpy(target.astype(np.float32)).to(device)[:, None]


class Net(nn.Module):
    def __init__(self, hidden):
        super().__init__()
        self.ft = nn.EmbeddingBag(768, hidden, mode="sum")
        self.ft_bias = nn.Parameter(torch.zeros(hidden))
        self.out = nn.Linear(2 * hidden, 1)
        nn.init.normal_(self.ft.weight, 0, 0.1)
        nn.init.normal_(self.out.weight, 0, 1 / math.sqrt(2 * hidden))
        nn.init.zeros_(self.out.bias)

    def forward(self, us, them, w):
        a = self.ft(us, per_sample_weights=w) + self.ft_bias
        b = self.ft(them, per_sample_weights=w) + self.ft_bias
        x = torch.cat([a, b], dim=1).clamp(0, 1).square()
        return self.out(x)

    def clip(self):
        # Keep quantized weights inside int16 range for the engine's integer path.
        with torch.no_grad():
            self.ft.weight.clamp_(-127 / QA, 127 / QA)
            self.out.weight.clamp_(-32767 / QB, 32767 / QB)


def export(net, path, hidden, meta):
    ft_w = torch.round(net.ft.weight.detach().cpu() * QA).to(torch.int16).numpy()      # [768, H]
    ft_b = torch.round(net.ft_bias.detach().cpu() * QA).to(torch.int16).numpy()        # [H]
    out_w = torch.round(net.out.weight.detach().cpu()[0] * QB).to(torch.int16).numpy()  # [2H]
    out_b = int(round(net.out.bias.item() * QA * QB))

    def arr(a, per_line=24):
        flat = a.reshape(-1).tolist()
        return "\n".join("    " + ", ".join(str(v) for v in flat[i:i + per_line]) + ","
                         for i in range(0, len(flat), per_line))

    with open(path, "w") as f:
        f.write("#pragma once\n\n// Generated by tools/nnue/train.py. " + meta + "\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"namespace nnue_weights {{\nconstexpr int HIDDEN = {hidden};\n")
        f.write(f"constexpr int QA = {QA}, QB = {QB}, SCALE = {SCALE};\n")
        f.write(f"alignas(64) constexpr std::int16_t FT_WEIGHTS[768 * {hidden}] = {{\n{arr(ft_w)}\n}};\n")
        f.write(f"alignas(64) constexpr std::int16_t FT_BIAS[{hidden}] = {{\n{arr(ft_b)}\n}};\n")
        f.write(f"alignas(64) constexpr std::int16_t OUT_WEIGHTS[{2 * hidden}] = {{\n{arr(out_w)}\n}};\n")
        f.write(f"constexpr std::int32_t OUT_BIAS = {out_b};\n}} // namespace nnue_weights\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("data", nargs="+")
    ap.add_argument("--hidden", type=int, default=256)
    ap.add_argument("--epochs", type=int, default=30)
    ap.add_argument("--batch", type=int, default=16384)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--lam", type=float, default=0.3, help="weight of the game result in the target")
    ap.add_argument("--out", default="nnue_weights.h")
    args = ap.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    recs = np.concatenate([np.asarray(load(p)) for p in args.data])
    rng = np.random.default_rng(0)
    rng.shuffle(recs)
    n_val = min(max(10000, len(recs) // 100), len(recs) // 5)
    val, train = recs[:n_val], recs[n_val:]
    print(f"{len(train):,} training / {len(val):,} validation positions on {device}")

    net = Net(args.hidden).to(device)
    opt = torch.optim.AdamW(net.parameters(), lr=args.lr, weight_decay=0.0)
    steps_per_epoch = len(train) // args.batch
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs * steps_per_epoch, eta_min=args.lr * 0.01)
    val_feats, val_t = features(val, device), targets(val, args.lam, device)

    t0 = time.time()
    for epoch in range(1, args.epochs + 1):
        order = rng.permutation(len(train))
        net.train()
        total = 0.0
        for step in range(steps_per_epoch):
            batch = train[order[step * args.batch:(step + 1) * args.batch]]
            us, them, w = features(batch, device)
            pred = torch.sigmoid(net(us, them, w))
            loss = torch.mean((pred - targets(batch, args.lam, device)) ** 2)
            opt.zero_grad(set_to_none=True)
            loss.backward()
            opt.step()
            sched.step()
            net.clip()
            total += loss.item()
        net.eval()
        with torch.no_grad():
            vloss = torch.mean((torch.sigmoid(net(*val_feats)) - val_t) ** 2).item()
        print(f"epoch {epoch:3d}  train {total / steps_per_epoch:.6f}  val {vloss:.6f}  ({time.time() - t0:.0f}s)",
              flush=True)

    meta = (f"{len(train):,} positions, hidden {args.hidden}, {args.epochs} epochs, "
            f"lambda {args.lam}, final val MSE {vloss:.6f}")
    export(net, args.out, args.hidden, meta)
    torch.save(net.state_dict(), args.out + ".pt")
    print("wrote", args.out)


if __name__ == "__main__":
    main()
