#pragma once

#include "position.h"

// Neural-network evaluation, side to move's point of view, in centipawns.
// Weights are compiled in from nnue_weights.h (generated by tools/nnue/train.py).
int nnue_evaluate(const Position& pos);
