#pragma once

#include <cstdint>

// Neural-network evaluation. Weights are compiled in from nnue_weights.h
// (generated by tools/nnue/train.py); NNUE_HIDDEN must match the network.
constexpr int NNUE_HIDDEN = 256;

// First-layer activations for both perspectives. Position keeps one up to
// date move by move, so an evaluation costs only the output layer.
struct Accumulator {
    alignas(64) std::int16_t v[2][NNUE_HIDDEN];
};

void nnue_reset(Accumulator& acc);
void nnue_add(Accumulator& acc, int pc, int sq);
void nnue_sub(Accumulator& acc, int pc, int sq);

class Position;
// Side to move's point of view, in centipawns.
int nnue_evaluate(const Position& pos);
